// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOaUoDZWU4WBxGq1NVlmW3L1wf51nPNss',
    appId: '1:100791974111:web:59485d9774be246336916a',
    messagingSenderId: '100791974111',
    projectId: 'aqua-med',
    authDomain: 'aqua-med.firebaseapp.com',
    storageBucket: 'aqua-med.firebasestorage.app',
    measurementId: 'G-4HCWG3WCXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_542OyhUy60AgwdQ3vSTvEcw4FVOpH14',
    appId: '1:100791974111:android:ec93818df481462736916a',
    messagingSenderId: '100791974111',
    projectId: 'aqua-med',
    storageBucket: 'aqua-med.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIPTy057O6PFsCgW34SRrKweoaTCBGb9I',
    appId: '1:100791974111:ios:83fbd66775e88adf36916a',
    messagingSenderId: '100791974111',
    projectId: 'aqua-med',
    storageBucket: 'aqua-med.firebasestorage.app',
    iosBundleId: 'com.example.aguaMed',
  );
}
